src/Entity/Recettes.php
<?php

namespace App\Entity;

use App\Repository\RecettesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecettesRepository::class)
 */
class Recettes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_enseigne;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_burger;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pain;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $viande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sauce;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fromage;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEnseigne(): ?string
    {
        return $this->nom_enseigne;
    }

    public function setNomEnseigne(string $nom_enseigne): self
    {
        $this->nom_enseigne = $nom_enseigne;

        return $this;
    }

    public function getNomBurger(): ?string
    {
        return $this->nom_burger;
    }

    public function setNomBurger(string $nom_burger): self
    {
        $this->nom_burger = $nom_burger;

        return $this;
    }

    public function getPain(): ?string
    {
        return $this->pain;
    }

    public function setPain(string $pain): self
    {
        $this->pain = $pain;

        return $this;
    }

    public function getViande(): ?string
    {
        return $this->viande;
    }

    public function setViande(string $viande): self
    {
        $this->viande = $viande;

        return $this;
    }

    public function getSauce(): ?string
    {
        return $this->sauce;
    }

    public function setSauce(string $sauce): self
    {
        $this->sauce = $sauce;

        return $this;
    }

    public function getFromage(): ?string
    {
        return $this->fromage;
    }

    public function setFromage(string $fromage): self
    {
        $this->fromage = $fromage;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use App\Entity\Ingredients;
use App\Entity\Recettes;

use App\Form\SearchForm;
use App\Repository\IngredientsRepository;
use App\Repository\RecettesRepository;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function index(Request $request, RecettesRepository $repo)
    {

        $form = $this->createForm(SearchForm::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $task = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();

            $pain_form = $form->get('pain')->getData()->getNomIngredient();
            $sauce_form = $form->get('sauce')->getData()->getNomIngredient();
            $viande_form = $form->get('viande')->getData()->getNomIngredient();
            $fromage_form = $form->get('fromage')->getData()->getNomIngredient();

            $recettes = $repo->findBy(
                array('pain' => $pain_form, 'sauce' => $sauce_form));
            // ... perform some action, such as saving the task to the database
            // for example, if Task is a Doctrine entity, save it!
            // $entityManager = $this->getDoctrine()->getManager();
            // $entityManager->persist($task);
            // $entityManager->flush();

            return $this->render('home/index_two.html.twig', [
                'form' => $form->createView(),
                'recettes' => $recettes,
              

            ]);

        }

        return $this->render('home/index.html.twig', [
            'form' => $form->createView(),
            'pain' => ''
        ]);
        }


    /**
     * @Route("/", name="app_home_two")
     */
    public function index2(): Response
    {
        return $this->render('home/index_two.html.twig', [
            
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}



{% block body %}

    <section id="background_home">

    
        
    </section>

    
    <section id="search_primary">

    <h2 style="text-align:center;">Compose ton burger</h2>


    <div id="search_primary_part_gauche" class="container-fluid">


     {{ form_start(form, { attr: { 'accept-charset' : 'utf-8', 'class' : 'row' }}) }}
		
        <div class="form_group col-5 offset-2">

          {{ form_label(form.pain) }}
		  {{ form_label(form.pain, 'Pain', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.pain) }}
          {{ form_errors(form.pain) }}
        
        </div>

         <div class="form_group col-5">

          {{ form_label(form.sauce) }}
		  {{ form_label(form.sauce, 'Sauce', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.sauce) }}
          {{ form_errors(form.sauce) }}
        
        </div>

         <div class="form_group col-5 offset-2">

          {{ form_label(form.viande) }}
		  {{ form_label(form.viande, 'Viande', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.viande) }}
          {{ form_errors(form.viande) }}
        
        </div>

         <div class="form_group col-5">

          {{ form_label(form.fromage) }}
		  {{ form_label(form.fromage, 'Fromage', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.fromage) }}
          {{ form_errors(form.fromage) }}
        
        </div>
        
		 
        <div class="form_group col-3 offset-8">

          {{ form_widget(form.send, {'label': "Valider mon burger"}) }}
        
        </div>
        
        {{ form_rest(form) }}
    {{ form_end(form) }}


    </div>

    
    
        <aside></aside>
    </section>

{% endblock %}

templates/home/index_two.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}



{% block body %}

    <section id="background_home">

        <div id="empty_top">
           
        </div>

        <div id="search_secondary">
            <p> 
                
                {% for recette in recettes %} 

                <div id="search_secondary_background">   

                {{ recette.nomBurger }}
                </br>
                {{ recette.pain }} - {{ recette.viande }} - {{ recette.sauce }} - {{ recette.fromage }}

                
                </div>
                
                {% endfor %}


            </p>
        </div>
        
    </section>


{% endblock %}